### ISSUE TITLE
Send a tweet out automagically when a deploy is created

### ISSUE THREAD

**Issue by mattyjones** [sensu-plugins/tom_servo#1]
https://dev.twitter.com/rest/reference/post/statuses/update

@sensu-plugins/contributors 

Thoughts?  This would be done using an automated webhook.  The use case is people could follow a twitter or even rss feed that only was for new versions of a plugin and they could do some sort of filtering to only get the plugins they want.

Right now this is just a cool itch I want to scratch at some point.

**Comment by majormoses** [comment]
@mattyjones I realize this is quite old, we already doing this with IRC is there any benefit over existing?
